<a href="https://colab.research.google.com/github/palomabareli/CienciaDeDadosLaboratorioComPandasEPython_20201106/blob/main/LaboratorioComPandasEPythonOcean.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Lista**: nativa do Python e mutável.

In [1]:
#Lista vazia
personList = list()

print(personList)

[]


**append()**: Adicionando elementos ao fim da lista.

In [3]:
personList.append('Paloma')
personList.append('Ribeiro')

print(personList)

['Paloma', 'Ribeiro']


In [4]:
personList.append('Bareli')

print(personList)

['Paloma', 'Ribeiro', 'Bareli']


Atualizando elementos da lista.

In [5]:
personList[1] = personList[2]
personList[2] = 'Ribeiro'

print(personList)

['Paloma', 'Bareli', 'Ribeiro']


O método **insert()** permite inserir registros na lista na posição informada.

In [6]:
personList.insert(0, 'Quem é')

print(personList)

personList.insert(0, 'Quem é')

print(personList)

['Quem é', 'Paloma', 'Bareli', 'Ribeiro']
['Quem é', 'Quem é', 'Paloma', 'Bareli', 'Ribeiro']


Removendo elementos da lista, se baseando em seu conteúdo, com o método **remove()**.

In [7]:
personList.remove('Quem é')

print(personList)

['Quem é', 'Paloma', 'Bareli', 'Ribeiro']


**Dicionários**: estrutura baseada em chave/valor. A chave é unica, mas os itens não.

Definindo um dicionário vazio.

In [8]:
numberDictionary = dict()

print(numberDictionary)

{}


Incluindo um novo elemento no dicionário.

In [9]:
numberDictionary['key'] = 'value'

print(numberDictionary)

{'key': 'value'}


O método **setdefault()** permite inserir um registro default no dicionário.

In [10]:
numberDictionary.setdefault(2)

print(numberDictionary)

{'key': 'value', 2: None}


**Pandas**: biblioteca destinada para manipulação de dados.

In [11]:
import pandas as pd

features = pd.read_csv('https://raw.githubusercontent.com/paulosalvatore/RandomForest_Pandas/master/temps.csv')
features.head(5)

year  month  day  week  ...  forecast_noaa  forecast_acc  forecast_under  friend
0  2016      1    1   Fri  ...             43            50              44      29
1  2016      1    2   Sat  ...             41            50              44      61
2  2016      1    3   Sun  ...             43            46              47      56
3  2016      1    4   Mon  ...             44            48              46      53
4  2016      1    5  Tues  ...             46            46              46      41

[5 rows x 12 columns]

**shape()**: formato do dataset (linhas por colunas).

In [12]:
print('The shape of our features is:', features.shape)

The shape of our features is: (348, 12)


**.describe()**: descrição estatística dos dados (melhor utilizada em campos categóricos)

In [13]:
features.describe()

year       month         day  ...  forecast_acc  forecast_under      friend
count   348.0  348.000000  348.000000  ...    348.000000      348.000000  348.000000
mean   2016.0    6.477011   15.514368  ...     62.373563       59.772989   60.034483
std       0.0    3.498380    8.772982  ...     10.549381       10.705256   15.626179
min    2016.0    1.000000    1.000000  ...     46.000000       44.000000   28.000000
25%    2016.0    3.000000    8.000000  ...     53.000000       50.000000   47.750000
50%    2016.0    6.000000   15.000000  ...     61.000000       58.000000   60.000000
75%    2016.0   10.000000   23.000000  ...     72.000000       69.000000   71.000000
max    2016.0   12.000000   31.000000  ...     82.000000       79.000000   95.000000

[8 rows x 11 columns]

**get_dummies()**: pega as variáveis categóricas e converte em valores dummy ou variáveis de indicador.


In [15]:
features = pd.get_dummies(features)
features.head(5)

year  month  day  temp_2  ...  week_Sun  week_Thurs  week_Tues  week_Wed
0  2016      1    1      45  ...         0           0          0         0
1  2016      1    2      44  ...         0           0          0         0
2  2016      1    3      45  ...         1           0          0         0
3  2016      1    4      44  ...         0           0          0         0
4  2016      1    5      41  ...         0           0          1         0

[5 rows x 18 columns]

**iloc**: seleciona um conjunto de linhas se baseando no índice.

In [16]:
features.iloc[:,5:].head(5)

average  actual  forecast_noaa  ...  week_Thurs  week_Tues  week_Wed
0     45.6      45             43  ...           0          0         0
1     45.7      44             41  ...           0          0         0
2     45.8      41             43  ...           0          0         0
3     45.9      40             44  ...           0          0         0
4     46.0      44             46  ...           0          1         0

[5 rows x 13 columns]

**Numpy**: biblioteca destinada a conversão de arrays.

In [17]:
import numpy as np

# Dados para predição
labels = np.array(features['actual'])
print(labels)

[45 44 41 40 44 51 45 48 50 52 45 49 55 49 48 54 50 54 48 52 52 57 48 51
 54 56 57 56 52 48 47 46 51 49 49 53 49 51 57 62 56 55 58 55 56 57 53 51
 53 51 51 60 59 61 60 57 53 58 55 59 57 64 60 53 54 55 56 55 52 54 49 51
 53 58 63 61 55 56 57 53 54 57 59 51 56 64 68 73 71 63 69 60 57 68 77 76
 66 59 58 60 59 59 60 68 77 89 81 81 73 64 65 55 59 60 61 64 61 68 77 87
 74 60 68 77 82 63 67 75 81 77 82 65 57 60 71 64 63 66 59 66 65 66 66 65
 64 64 64 71 79 75 71 80 81 92 86 85 67 65 67 65 70 66 60 67 71 67 65 70
 76 73 75 68 69 71 78 85 79 74 73 76 76 71 68 69 76 68 74 71 74 74 77 75
 77 76 72 80 73 78 82 81 71 75 80 85 79 83 85 88 76 73 77 73 75 80 79 72
 72 73 72 76 80 87 90 83 84 81 79 75 70 67 68 68 68 67 72 74 77 70 74 75
 79 71 75 68 69 71 67 68 67 64 67 76 77 69 68 66 67 63 65 61 63 66 63 64
 68 57 60 62 66 60 60 62 60 60 61 58 62 59 62 62 61 65 58 60 65 68 59 57
 57 65 65 58 61 63 71 65 64 63 59 55 57 55 50 52 55 57 55 54 54 49 52 52
 53 48 52 52 52 46 50 49 46 40 42 40 41 36 44 44 43

In [18]:
# Removendo o label do dataset, onde axis = 1 se refere a coluna.
features= features.drop('actual', axis = 1)
print(features)

     year  month  day  temp_2  ...  week_Sun  week_Thurs  week_Tues  week_Wed
0    2016      1    1      45  ...         0           0          0         0
1    2016      1    2      44  ...         0           0          0         0
2    2016      1    3      45  ...         1           0          0         0
3    2016      1    4      44  ...         0           0          0         0
4    2016      1    5      41  ...         0           0          1         0
..    ...    ...  ...     ...  ...       ...         ...        ...       ...
343  2016     12   27      42  ...         0           0          1         0
344  2016     12   28      42  ...         0           0          0         1
345  2016     12   29      47  ...         0           1          0         0
346  2016     12   30      48  ...         0           0          0         0
347  2016     12   31      48  ...         0           0          0         0

[348 rows x 17 columns]


In [19]:
# Salvando o dataset para uso futuro.
feature_list = list(features.columns)
print(feature_list)

['year', 'month', 'day', 'temp_2', 'temp_1', 'average', 'forecast_noaa', 'forecast_acc', 'forecast_under', 'friend', 'week_Fri', 'week_Mon', 'week_Sat', 'week_Sun', 'week_Thurs', 'week_Tues', 'week_Wed']


In [20]:
# Convertendo para um array Numpy
features = np.array(features)
print(features)

[[2.016e+03 1.000e+00 1.000e+00 ... 0.000e+00 0.000e+00 0.000e+00]
 [2.016e+03 1.000e+00 2.000e+00 ... 0.000e+00 0.000e+00 0.000e+00]
 [2.016e+03 1.000e+00 3.000e+00 ... 0.000e+00 0.000e+00 0.000e+00]
 ...
 [2.016e+03 1.200e+01 2.900e+01 ... 1.000e+00 0.000e+00 0.000e+00]
 [2.016e+03 1.200e+01 3.000e+01 ... 0.000e+00 0.000e+00 0.000e+00]
 [2.016e+03 1.200e+01 3.100e+01 ... 0.000e+00 0.000e+00 0.000e+00]]


**Skicit-learn**: biblioteca destinada a tratamento e análise de modelos preditivos.

In [21]:
from sklearn.model_selection import train_test_split

O Skicit-learn será usado para dar um split nos dados em dois datasets: treino e teste.

In [23]:
train_features, test_features, train_labels, test_labels = train_test_split(features, labels, test_size = 0.25, random_state = 42)

Avaliando o tamanho dos datasets que seram analisados.

In [24]:
print('Training Features Shape:', train_features.shape)
print('Training Labels Shape:', train_labels.shape)
print('Testing Features Shape:', test_features.shape)
print('Testing Labels Shape:', test_labels.shape)

Training Features Shape: (261, 17)
Training Labels Shape: (261,)
Testing Features Shape: (87, 17)
Testing Labels Shape: (87,)


A baseline de predição será o histórico do campo average.

In [26]:
baseline_preds = test_features[:, feature_list.index('average')]
print('The baseline predictions: ', round(np.mean(baseline_preds), 2))

The baseline predictions:  59.2


Formando a baseline de erros:

In [27]:
# Baseline errors, and display average baseline error
baseline_errors = abs(baseline_preds - test_labels)
print('The average baseline error: ', round(np.mean(baseline_errors), 2))

The average baseline error:  5.06
